pydeseq2/DeseqDataSet.py, pydeseq2/utils.py, tests/test_edge_cases.py
This PR implements tests on the count matrix. More precisely:
- The `DeseqDataset` class now runs `test_valid_counts` at initialisation and throws a ValueError in case of unexpected inputs,
- Pytests now test that an error is thrown in case a `DeseqDataset` is initialised with NaN, non-integer or negative values in the count matrix,
- Pytests test the behaviour of  `DeseqDataset` and `DeseqStats` when a gene only has zero counts for all samples.
=> CI: implement tests for count matrices

pydeseq2/DeseqDataSet.py, pydeseq2/utils.py, tests/test_edge_cases.py
This PR implements tests on the design factor in the clinical data. More precisely:
- The `DeseqDataset` class now tests whether the design factor contains NaN values and checks the design factors takes exactly 2 values. 
- Pytests now test that an error is thrown in case a `DeseqDataset` is initialised with NaNs, or not exactly two values in the design factor.
DO NOT MERGE: there are a few tests that remain to be implemented
=> CI: implement tests for design factors

pydeseq2/DeseqDataSet.py, tests/test_edge_cases.py
This PR fixes an issue that appears when the count matrix and the clinical data provided to a `DeseqDataSet` have identical sets of samples, but in a different order, by sorting the indices at initialization.
=> Index sorting

pydeseq2/utils.py, tests/test_edge_cases.py
This PR aims to fix the bug described in Issue #43.
The issue seemed to be that the summation was done on the wrong axis in the `trimmed_variance` function, called through `robust_method_of_moments_disp` in the  `calculate_cooks` method of the `DeseqDataSet` class.
=> Fix: calculate Cooks distances with few samples 

pydeseq2/DeseqStats.py
With PR #40 the `_change_lfc_sign` attribute of the `DeseqStats` class has deprecated. This PR removes it, along with a useless print statement (intended for debugging only).
=> Refactor: remove deprecated `_change_lfc_sign` attribute of the `DeseqStats` class

pydeseq2/DeseqStats.py, tests/test_edge_cases.py
This PR addresses issue #46 by raising an `AssertionError` if one tries to initialize a `DeseqStats` object  from a `DeseqDataSet` with `refit_cooks=True` but whose outliers were not refit. 
This is detected by checking that the `DeseqDataSet` has a `replaced` attribute. 
A corresponding pytest was also added.
Closes #46.
=> Fix: raise error when cooks outliers should have been refitted but were not

docs/source/api/DeseqDataSet.rst, docs/source/api/DeseqStats.rst, docs/source/api/grid_search.rst, docs/source/api/index.rst, docs/source/api/preprocessing.rst, docs/source/api/utils.rst, docs/source/conf.py
Adds the autosummary for the api: meaning the table with short description for docstrings
now it looks like this:
and this:
=> DOC autosummary for api

README.md, datasets/README.md, notebooks/PyDESeq2_minimal_example.ipynb, notebooks/PyDESeq2_step_by_step_pipeline.ipynb, notebooks/README.md, pydeseq2/utils.py
This PR removes any type of support for TCGA data (in the `load_example_data` function and `notebooks` directory in particular).
This is because we do not provide the data ourself, nor do we provide a script or simple instructions to obtain this data.
=> BENCH remove support for TCGA data

pydeseq2/DeseqDataSet.py
This PR adds the `joblib_verbosity` attribute of `DeseqDataSet`, which allows to control the level of verbosity of `Parallel` worker pools, as an argument in the main loop of `fit_genewise_dispersions`, from which it was missing.
=> Fix add missing `joblib_verbosity` argument in `fit_genewise_dispersions`

docs/requirements.txt, setup.py
This PR is not linked to an existing issue.
This PR moves the specific requirements of the documentation (`matplotlib` and `gitpython`) which are currently in the `setup.py` file to the `docs/requirements.txt` file, which is more appropriate as they are not used elsewhere.
=> Moving docs' requirements into the actual docs' requirements file

pydeseq2/dds.py, pydeseq2/ds.py, tests/test_edge_cases.py
Fixes #69.
- If no cohort has enough samples to refit, set the `replaced` attribute to `False` for all genes in a `DeseqDataSet`,
- Skip empty cutoffs in `DeseqStats`'s `_independent_filtering`,
- Add a unit test to check that the issue described in #69 no longer occurs.
=> BUG set `dds.replaced` to `False` if cohorts don't have enough samples

.github/workflows/pr_validation.yml, .pre-commit-config.yaml, pydeseq2/dds.py
update workflow to run pre-commit to avoid redundant code (in workflow and in precommit)
when adding mypy to pre-commit, CI should automatically run it as well #68 
It removes the checking of the linting from the workflow and instead it runs pre-commit which has those checks included
=> CI update workflow

.github/workflows/pr_validation.yml, README.md
Python 3.8 is supported until October 2024. To ensure the long term support we need to start testing for newer versions of Python as well
NA
CI check for python 3.9 and 3.10 and 3.11
=> CI add more versions of python to the github workflow

pydeseq2/utils.py, tests/test_edge_cases.py, tests/test_utils.py
This PR fixes the example gallery which causes the docs not to compile on readthedocs. This is due to a data importing issue after merging #68 (pandas won't load a csv from an url provided in the form of a `Path`).
A unit test was added to `test_utils.py` to check that `load_example_data` correctly retrieves data from github when the `datasets` directory is not accessible (as when building the docs on RTD).
=> DOC fix broken RTD example gallery

docs/requirements.txt, docs/source/conf.py, pydeseq2/dds.py, pydeseq2/ds.py, pydeseq2/grid_search.py, pydeseq2/preprocessing.py, pydeseq2/utils.py
Fixes #86 
This PR improves the display of parameters and returns types in the documentation.
Before: 
After:
=> DOC Improve parameter type display

pydeseq2/dds.py
This PR fixes a small typo in an attribute name (`self.new_all_zero_genes` instead of `self.new_all_zeroes_genes`).
=> BUG typo in attribute name

pydeseq2/dds.py
This PR corrects a typo which caused the dispersion prior estimate to be incorrect.
=> BUG correct typo in `fit_dispersion_prior`

pydeseq2/dds.py, pyproject.toml, tests/test_edge_cases.py
This PR fixes a bug (incompatible boolean mask and array shapes, encountered when testing on TCGA-PAAD) which appeared when trying to refit cooks outliers for datasets in which some samples are un-replaceable due to not having enough replicates.
It also implements a test to ensure that the code runs error-free in that setting.
=> BUG fix replacement counts when there are un-replaceable samples

examples/plot_minimal_pydeseq2_pipeline.py, examples/plot_step_by_step.py, pydeseq2/dds.py, pydeseq2/utils.py, tests/test_edge_cases.py, tests/test_pydeseq2.py
Fixes #94 
This PR provides the option to initialize an `DeseqDataSet` by passing an `AnnData` as an argument.
=> ENH allow initializing a DeseqDataSet from an AnnData object

pydeseq2/dds.py
In the dispersion prior variance step, the expected variance of the log dispersion involves a function of (m - p), number of samples minus number of columns of model matrix. Compare to:
https://github.com/mikelove/DESeq2/blob/devel/R/core.R#L1182
I'm trying to align some of the parameters a bit.
=> BUG dispersion prior variance

pydeseq2/dds.py, pydeseq2/utils.py
This PR fixes bugs when using `pydeseq2` with `pandas` 2.0.
```
counts_df = load_example_data(
modality="raw_counts",
dataset="synthetic",
debug=False,
)
clinical_df = load_example_data(
modality="clinical",
dataset="synthetic",
debug=False,
)
dds = DeseqDataSet(
counts=counts_df,
clinical=clinical_df,
refit_cooks=True,
design_factors="condition",
)
dds.deseq2()
```
would output
```
Fitting size factors...
... done in 0.00 seconds.
Fitting dispersions...
UFuncTypeError: Cannot cast ufunc 'slogdet' input from dtype('O') to dtype('float64') with casting rule 'same_kind'
```
After fixing the first bug, `DeseqDataSet.refit()` would throw `anndata.ImplicitModificationWarning`s, making the tests fail. 
The first bug is caused by `pydeseq2.utils.build_design_matrix` outputting boolean columns …
=> BUG fix slogdet bug

pydeseq2/dds.py, setup.py, tests/test_pydeseq2.py
Fixes #114 
Expands anndata compatibility
=> Expand anndata compatibility

pydeseq2/preprocessing.py, tests/test_pydeseq2.py
Fixes #122 
This PR:
- Fixes the bug described in #122 appearing when calling `deseq2_norm` on a pandas dataframe, by checking whether the argument is a dataframe (in which case indexing is done with `.loc` or a ndarray).
- Implements a test to check that we get the same results in both cases.
=> BUG fix `deseq2_norm` bug when applied to a pandas dataframe

pydeseq2/dds.py, pydeseq2/utils.py, tests/test_edge_cases.py
Fixes #132
* Initializes `beta` with log mean (normalized) counts when the design is not a full rank matrix.
This as such is not enough, because (as currently defined) the model cannot be fitted if the design matrix does not have full column rank. Hence, similarly to the [DESeq2](https://github.com/mikelove/DESeq2/blob/2c3c14cbfa09300e503e08302c60ddf112beacfd/R/AllClasses.R#L295) R package, this PR:
* Checks that the design matrix has full column rank at `DeseqDataSet` initialisation,
* Implements a test to check that a `ValueError` is thrown when the design matrix has deficient column rank.
=> BUG `beta` not initialized in `irls_solver` when the design is not a full rank matrix

pydeseq2/ds.py, tests/test_edge_cases.py
Fixes #121 
This PR addresses #121 (wrong display of shrunk factors). More precisely:
- the message output by `lfc_shrink` was fixed to match the coefficient that was actually shrunk
- when the coefficient is not available, the error message now explains how to set `ref_level` in `DeseqDataSet`
- it is now possible to set `coeff=None`
- `coeff=None` is tested in `test_edge_cases.py`
=> BUG wrong `lfc_shrink` sign display

.github/workflows/pr_validation.yml
This PR implements a nightly CI run on every week day. Currently, the CI runs only when pull requests are submitted, which is infrequent. This prevents us from catching bugs due to version bumps early. These nightly tests will help developers catch them as soon as they arise.
=> cron scheduler: CI runs every week day at 3:30 UTC

pydeseq2/dds.py, pydeseq2/utils.py
This PR addresses issue #124 and implements functionality to create a dispersion plot (similar to `plotDispEsts()` in DESeq2). 
PR includes a `make_scatter()` function (based on matplotlib) in utils.py that is then called by `plot_dispersions()` in dds.py. `plot_dispersions()` currently just graphs estimated, fitted, and final dispersions -- let me know if more flexibility would be appropriate. Also, I'm happy to add any documentation and address any feedback/further changes you'd like to see in the code!
=> Add plot_dispersions() 

pydeseq2/utils.py
Fixes a bug when `save_path` is not `None` in `plot_dispersions`.
=> BUG check that `save_path` is not `None` before saving in `plot_dispersions`

pydeseq2/dds.py, tests/test_edge_cases.py
Fixes #136 
Throw a `UserWarning` instead of a `ValueError` when a `DeseqDataSet` is initialized with a rank-deficient design matrix.
This allows users to run design-free VST without providing a full rank design (as described in #136).
=> MAINT turn rank deficiency exception to warning

pydeseq2/dds.py
The `ref_level` argument is missing from `sub_dds` in `_refit_without_outliers`. This can result in LFCs having the wrong sign for genes whose parameters are refitted.
=> BUG add ref_level argument to sub_dds when refitting cooks outliers

pydeseq2/dds.py, pydeseq2/ds.py
This is in reference to issue #102, i.e. introducing a quiet parameter to suppress status updates.
1. This introduces a `self.quiet` bool attribute to the `DeseqDataSet` class
2. Functions that `print` first check if the `self.quiet` attribute is set and only print if so
3. Print statements are routed to `sys.stderr` as opposed to stdout (this wasn't in the issue but I find this to be more standard for status updates like this)
=> Introduce quiet attribute to `DeseqDataSet` that is checked before printing status updates

pydeseq2/dds.py, tests/test_edge_cases.py
As pointed out by @mikelove, in the corner case where the design matrix has fewer than 3 degrees of freedom, the distribution of log dispersions is poorly estimated by the MAD, as in `fit_dispersion_prior` (cf the [DESeq2](https://github.com/mikelove/DESeq2/blob/24099effd42f31b96bf7c867ea03d7300a6368bc/R/core.R#L631) implementation of `estimateDispersionsPriorVar`).
This is a relatively minor issue that should be addressed in the future. Meanwhile, this PR:
- updates the docstring of `fit_dispersion_prior` to reflect this issue,
- raises a warning when this corner case arises.
=> DOC Degrees of freedom corner case

pydeseq2/ds.py, pydeseq2/utils.py, tests/test_edge_cases.py
There is no existing issue that I saw that is requesting this functionality.
This PR uses matplotlib to implement a `plotMA()` function. 
The MA plot shows the mean of the normalized counts versus the log2 fold changes for all genes tested. Genes that are significantly differentially expressed (based on some user-specified threshold) are colored red; the non-significant genes are colored grey. This plot can be helpful to look at LFC shrinkage effects. 
This functionality tries to copy the version of `plotMA()` in R. Example: 
A couple of considerations I wanted to flag:
1. Rows that return NaN in padj are colored grey and ultimately ignored (let me know if you'd like me to change this behavior, I think in R they are also ignored?)
2. I modify the results_df to add a new column, color. …
=> add plotMA() functionality

pydeseq2/dds.py, pydeseq2/utils.py
This PR is a minor refactoring of `DeseqDataSet._fit_rough_dispersions()`.
Currently, this method takes both `counts` and `size_factors` as arguments, only to compute normalized factors as `counts / size_factors[:, None]`.
We now provide `normed_counts` directly, which are already stored in `self.layers["normed_counts"]` when `_fit_rough_dispersions()` is called in the pydeseq2 pipeline.
Likewise, we provide `normed_counts` instead of `counts` in `_fit_moments_dispersions()` to avoid performing the division again.
=> MAINT reduce the number of arguments in ``_fit_rough_dispersions``

.github/workflows/pr_validation.yml
Closes #170 
Following @ivirshup's suggestion, this PR adds tests against pre-release versions of pydeseq2's dependencies to the CI.
=> ci: test against pre-release versions of dependencies

pydeseq2/utils.py, tests/test_edge_cases.py
Related to #174
Throws an error when the design matrix has the same number of rows and columns, as it is not possible to fit rough dispersions in this case. This reproduces the behavior of DESeq2.
=> BUG division by zero when ``num_samples == num_vars``

.github/workflows/pr_validation.yml
With pre-commit ci, this step is no longer necessary and blocks testing the actual code
=> Remove precommit from workflow

pydeseq2/dds.py
In `dds._refit_without_outliers`, the `obsm["size_factors"]` of `sub_dds` should be the same as the original object when computing genewise dispersions.
However, since version 0.4.1, the `_fit_MoM_dispersions` method (called by `fit_genewise_dispersions`) first checks if a `normed_counts` layer exists, and if not, runs `fit_size_factors`.
This caused size factors to be overwritten in `dds._refit_without_outliers`.
To fix this, this PR sets the `normed_counts` layer in `sub_dds` before computing genewise dispersions.
=> BUG set normed_counts in sub_dds before recomputing genewise dispersions when refitting

pyproject.toml
Related to github actions test recently failing.
s
The test suite failed due to a `DeprecationWarning` raised by `pandas.core.dtypes.common.is_categorical_dtype`. This function is imported by `patsy`, which as dependency of `pandas`.
This PR temporarily fixes this issue by ignoring `DeprecationWarning`s from `patsy`.
Once this issue is fixed in `patsy` or `statsmodels`, this filter should be removed.
=> TST: ignore the DeprecationWarning from pandas `is_categorical_dtype`

pyproject.toml
Ignore pandas' warning that v3.0 will require Pyarrow
=> CI: ignore the deprecation warning about the future Pyarrow dependency

examples/plot_minimal_pydeseq2_pipeline.py, pydeseq2/dds.py, pydeseq2/default_inference.py, pydeseq2/inference.py
Fixes #214
Adding back n_cpus as an optional keyword argument in DeseqDataSet, and adding `n_cpus` as an abstract property in the Inference class, in order to override the cpus of the `inference` instance passed to DeseqDataSet (let me know if you prefer to not have that and just have a warning instead).
=> Add back n_cpus argument in DeseqDataSet

.github/workflows/pr_validation.yml, README.md, docs/source/conf.py, docs/source/usage/requirements.rst, pydeseq2/dds.py, pydeseq2/default_inference.py, pydeseq2/ds.py, pydeseq2/inference.py, pydeseq2/utils.py, pyproject.toml, setup.py, tests/test_edge_cases.py
(Partially) fixes #231, closes #235
This PR removes pydeseq2's dependence on statsmodels, which has been causing a few bugs recently (and is the reason why the CI currently fails).
Statsmodels was used to:
- fit a gamma GLM in `fit_dispersion_trend` 
- -> this PR replaces it with a custom implementation based on `scipy.optimize`'s L-BFGS-B (which incidentally solves the negative coefficients issue #231). When the fit fails, the code switches to a mean fit.
- perform multiple test adjustment 
- -> replaced by [`scipy.stats.false_discovery_control`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.false_discovery_control.html)
- perform lowess (locally weighted regression) in `DeseqStats._independent_filtering` 
- -> replaced by a custom implementation adapted from …
=> MAINT Remove statsmodels

pydeseq2/dds.py, pydeseq2/default_inference.py, pydeseq2/ds.py, tests/test_edge_cases.py
Fixes #237, closes #238
This PR fixes a bug arising when all genes whose Cooks outliers are replaced lead to all-zero values (cf #237).
To fix this, it introduces (similarly to [DESeq2](https://github.com/thelovelab/DESeq2/blob/0247fd7b814c47853891aefe06a127721927333d/R/core.R#L2492)) a new `varm` field, `"refitted"`, which complements `"replaced"` by indicating whether dispersions and LFCs were refitted for that gene (on top of its having values replaced).
Finally, the faulty example presented in #237 was added to the test suite.
=> BUG Fix new all zero replace

pydeseq2/ds.py, pydeseq2/grid_search.py, pydeseq2/utils.py
- Fix the rendering of latex formula in docstring when making html doc with sphinx, by transforming all "\\" into "\".
I checked the result by rebuilding the doc and checking that the formulae are properly rendered.
Before:
After:
- I did not check whether the formulae were right, but just that they were well-displayed.
--
When compiling the doc, I get the following warning due to cycling import:
```
WARNING: autodoc: failed to import module 'grid_search' from module 'pydeseq2'; the following exception was raised:
cannot import name 'grid_fit_alpha' from partially initialized module 'pydeseq2.grid_search' (most likely due to a circular import) (/Users/owkin/Project/PyDESeq2/pydeseq2/grid_search.py)
```
Indeed `grid_search` imports `utils` and vice versa.  But I don't think it should be …
=> Fix: latex display in sphinx doc

pydeseq2/dds.py
Currently, when outlier genes are refitted, only `"_normed_means"`, `"LFC"` and `"dispersions"` are updated in the fields of the `DeseqDataSet`, but not `"genewise_dispersions"` and `"fitted_dispersions"`.
This has limited or no impact on the remainder of the code, but interferes with visualisation (e.g. with `plot_dispersions()`. 
This PR fixes this by also updating `"genewise_dispersions"` and `"fitted_dispersions"`.
Before:
After:
=> BUG update genewise dispersions and fitted dispersions of refitted genes

pydeseq2/utils.py
Fixes #280 
Initialize `beta_init` in irls even when the design matrix is not full rank.
This prevents a `referenced before assignment` error in the case where irls is run with a rank-deficient design matrix and irls starts diverging.
=> BUG initialize `beta_init` when the design matrix is not full rank

pydeseq2/dds.py, pydeseq2/ds.py, tests/test_edge_cases.py, tests/test_pydeseq2.py
Our pre-release complains about:
> E           AttributeError: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
=> Replace np.NaN with np.nan -> numpy 2.0 compat

pydeseq2/dds.py, tests/test_pydeseq2.py
Fix #263
Proposed solution :
- A `self.fit_type` is defined at class initialisation and will by default set the fit_type for DEA and VST.
- If needed, a fit type can be passed to deseq2() and vst() in order to launch the two analysis with a separate fit_type. It will set self.fit_type to the user one.
- self.vst_fit() and self.vst_transform() will call internally the self.fit_type.
- vst_transform() should always be called after vst_fit() or deseq2(). Raise an exception if needed trend_coef have not been computed by deseq2() or vst_fit()
- Add unit tests
=> fix : enable vst be used "blindly" and to fit its own dispersion

pydeseq2/ds.py
Make `DeseqStats.summary()` function also rely on `quiet` parameter for verbose.
=> summary function uses quiet to print

pydeseq2/dds.py
This PR is to fix Issue #288 .
The current initialization of `DeseqDataSet` always overwrites its `Inference` object's `n_cpus`. So no matter which value is specified for `n_cpus` when declaring an `Inference` object, when passed to `DeseqDataSet`, its `n_cpus` is always overwritten to use all available vCPUs.
My implementation just restricts that Inference's `n_cpus` can only be overwritten if DeseqDataSet's `n_cpus` is not `None`.
=> Fix Inference n_cpus overwritten issue

pydeseq2/dds.py
Related to #291
When we create a DeseqDataSet from a counts and a metadata dataframes, counts are automatically cast to int, but not when we create one from a pre-existing anndata object. 
This may apparently cause bugs (cf. #291). 
This PR fixes this by casting anndata counts to int by default.
=> MAINT cast counts to int when initialising a DeseqDataSet from anndata

pydeseq2/ds.py
Currently, `DeseqStats.lfc_shrink` does not respect `self.quiet` when printing `self.results_df` at the end of the method. This PR adds checks for `self.quiet` for the missing print statements.
=> Respect quiet=True in DeseqStats.lfc_shrink

pydeseq2/dds.py
Fixes #306 
Starting from v0.10.9, anndata no longer supports pandas DataFrames or Series in varm fields. 
This caused a bug when ``refit_cooks`` was set to ``True``, but no genes were replaced, as a ``varm["replaced"]`` was set as pandas Series filled with ``False``.
This PR fixes this issue by replacing the Series with a numpy array.
It also solves a second deprecation issue arising in `vst_fit`, in which a design matrix was uselessly set with `MultiIndex`columns, which are no longer supported by anndata.
Note: in the case were genes are replaced, ``varm["replaced"]`` is automatically defined as an array.
=> BUG set ``varm["replaced"]`` as a numpy array

pydeseq2/dds.py
Fixes #311
Sets ``vst_fit_type="mean"`` in case the parametric fit fails in ``vst_fit()``.
=> BUG set vst fit type to mean when parametric fails

pydeseq2/dds.py, pydeseq2/ds.py, tests/test_pydeseq2.py
The `replace_cooks` data was stored as a pandas DataFrame. This is memory inefficient for large data. It has been refactored from a DataFrame to a numpy array.
A new `low_memory` argument to `DeseqDataSet` is available. When set to True, large data arrays saved into the AnnData elements `.obsm` and `.layers` are deleted if there is no further use for them in the standard deseq workflow. This reduces peak memory consumption dramatically.
=> ENH: Memory Optimizations & low_memory Flag

pydeseq2/dds.py, tests/test_pydeseq2.py
Fixes #204 
Builds on #292
This PR adds an option to fit size factors from a set of control (house-keeping) genes only, by adding an attribute to `DeseqDataSet`.
Control genes had actually already been implemented (and tested) in #292, but until this PR there was no direct way to specify them when initializing a `DeseqDataSet`.
=> ENH add access to `control_genes` as a `DeseqDataSet` attribute

pydeseq2/dds.py, pydeseq2/ds.py
Fixes #287 
This PR ensures that no non-warning statements are printed in quiet mode. Main changes:
- The `quiet` attribute is passed to `sub_dds` in the cooks refitting step
- VST methods are now silent when `quiet=True`
=> MAINT fix quiet mode
